# Server port
server.port=8761

# Application name
spring.application.name=discovery-server

# Don't register the Eureka server with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Reduce startup wait time
eureka.server.wait-time-in-ms-when-sync-empty=0